<a href="https://colab.research.google.com/github/sangireddyharini/Harini_Reddy/blob/main/model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
scalar = np.array(5)
print("Scalar value :", scalar)

Scalar value : 5


In [ ]:
vector = np.array([1, 2, 3])
print("Vector values:",vector)

Vector values: [1 2 3]


In [ ]:
import numpy as np
scalar = np.array(5)
print("Scalar value:", scalar)
vector = np.array([1, 2, 3])
print("Vector values:", vector)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (Matrix):\n",matrix)
tensor_3d = np.array([[[1, 2, 3,], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Tensor:\n", tensor_3d)
tensor_4d = np.random.rand(2, 3, 4, 5)
print("Shape of 4D Tensor:", tensor_4d.shape)

Scalar value: 5
Vector values: [1 2 3]
2D Tensor (Matrix):
 [[1 2 3]
 [4 5 6]]
3D Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 4D Tensor: (2, 3, 4, 5)


In [9]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
def generate_data(num_samples):
  x1 = np.random.randint(0, 100, size=num_samples)
  x2 = np.random.randint(0, 100, size=num_samples)
  y = x1 + x2
  return np.vstack((x1, x2)).T, y
num_samples = 10000
x, y = generate_data(num_samples)
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X_train, y_train, epochs=72, batch_size=32, validation_split=0.2)
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
sample_input = np.array([[23, 45]])
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/72
200/200 [==============================] - 2s 4ms/step - loss: 1947.7345 - val_loss: 69.1046
Epoch 2/72
200/200 [==============================] - 1s 4ms/step - loss: 31.7276 - val_loss: 11.6164
Epoch 3/72
200/200 [==============================] - 1s 4ms/step - loss: 4.5782 - val_loss: 1.3600
Epoch 4/72
200/200 [==============================] - 1s 4ms/step - loss: 0.8700 - val_loss: 0.5485
Epoch 5/72
200/200 [==============================] - 1s 3ms/step - loss: 0.3439 - val_loss: 0.1833
Epoch 6/72
200/200 [==============================] - 1s 3ms/step - loss: 0.1434 - val_loss: 0.1060
Epoch 7/72
200/200 [==============================] - 0s 2ms/step - loss: 0.1010 - val_loss: 0.0821
Epoch 8/72
200/200 [==============================] - 0s 2ms/step - loss: 0.0788 - val_loss: 0.0659
Epoch 9/72
200/200 [==============================] - 0s 2ms/step - loss: 0.0638 - val_loss: 0.0552
Epoch 10/72
200/200 [==============================] - 0s 2ms/step - loss: 0.0539 - val_loss: 